### ISSUE TITLE
Comparison to existing SIMD base64 implementations.

### ISSUE THREAD

**Issue by TheThirdOne** [ilyakurdyukov/crzy64#1]
It would be nice if there were some direct comparison to base64 projects that use SSSE3, AVX2 or AVX-512. It would be nice to know if this actually beats state of the art base64 decoders, but it is a little hard to fairly compare without equivalent benchmarks. 

[Turbo-Base64](https://github.com/powturbo/Turbo-Base64) would be a good target because it includes a bunch of benchmarks to other code and seems to be the SOTA. Based on comparisons to memcpy I would actually expect this to be substantially slower than TurboBase SSE.

**Comment by ilyakurdyukov** [comment]
When replacing the TurboBase64 SSE core with the crzy64 SSSE3 core, the results are the same:

      E MB/s    size     ratio%   D MB/s   function

      3547.94       1336 133.60% 11671.75 crzy64sse        1000
      7499.98      13336 133.36% 12388.81 crzy64sse       10000
      8454.00     133336 133.34% 12445.56 crzy64sse      100000
      8581.39    1333336 133.33% 12446.24 crzy64sse     1000000
      7559.00   13333336 133.33% 10778.31 crzy64sse    10000000
      7336.18   26666668 133.33% 10550.89 crzy64sse    20000000

      3753.58       1336 133.60% 11674.91 tb64sse        1000
      7597.47      13336 133.36% 12383.66 tb64sse       10000
      8454.23     133336 133.34% 12440.92 tb64sse      100000
      8572.84    1333336 133.33% 12389.89 tb64sse     1000000
      7574.65   13333336 133.33% 10756.93 tb64sse    10000000
      7337.75   26666668 133.33% 10544.91 tb64sse    20000000

     80519.14       1000 100.00% 80361.96 memcpy        1000
     98073.64      10000 100.00% 64723.95 memcpy       10000
     49708.57     100000 100.00% 49149.18 memcpy      100000
     33309.42    1000000 100.00% 34288.40 memcpy     1000000
     14686.87   10000000 100.00% 14644.95 memcpy    10000000
     14029.36   20000000 100.00% 13955.93 memcpy    20000000

But in my benchmark it's only 6GB/s because I didn’t do perfetch for source data and have less unroll.

It looks like there are fewer vector operations in TB64, but they are very complex (so take more clock cycles than the basic ones, not available for some architectures and cannot be done as "SIMD within a register" (SWAR)).

You may notice that there is no SSE2 variant in TB64 because it requires advanced instructions.

**Comment by TheThirdOne** [comment]
Impressive stuff. Its actually very surprising just how similar the performance of crzy64sse and tb64sse are.

Thanks for indulging my curiosity and getting the comparison benchmark set up.

**Comment by ilyakurdyukov** [comment]
Now you can directly compare with TurboBase64 because I added benchmarking of the same sizes. But I still didn't use unrolling and prefetching, so the results from my benchmark is a little worse.

**Comment by ilyakurdyukov** [comment]
My impression is that Turbo Base64 measures MB/s of encoded data (which is 1.333 times more), while I measure MB/s of decoded data (which is less, but I think it is more correct), so my timers show 1.333 less performance.
